import { useState } from 'react';
import * as Dialog from '@radix-ui/react-dialog';
import { Plus, Search, Moon, Sun, Package, X, LayoutDashboard } from 'lucide-react';
type Product = { id:number; name:string; category:string; price:number; stock:number };
const initial:Product[]=[{id:1,name:'NovaBook Air',category:'Computadores',price:2450000,stock:12},{id:2,name:'Pulse Buds',category:'Audio',price:320000,stock:28},{id:3,name:'Orbit Watch',category:'Accesorios',price:580000,stock:7}];
const money=(n:number)=>n.toLocaleString('es-CO',{style:'currency',currency:'COP',maximumFractionDigits:0});
export default function App(){
 const [products,setProducts]=useState(initial); const [query,setQuery]=useState(''); const [dark,setDark]=useState(true);
 const [name,setName]=useState(''); const [category,setCategory]=useState(''); const [price,setPrice]=useState(''); const [stock,setStock]=useState(''); const [error,setError]=useState('');
 const visible=products.filter(p=>(p.name+' '+p.category).toLowerCase().includes(query.toLowerCase()));
 function add(e:React.FormEvent){e.preventDefault(); if(name.trim().length<2||!category.trim()||Number(price)<=0||!Number.isInteger(Number(stock))||Number(stock)<0){setError('Completa los campos. El nombre requiere 2 caracteres, el precio debe ser mayor que cero y el stock un entero no negativo.');return;} setProducts(prev=>[...prev,{id:Date.now(),name:name.trim(),category:category.trim(),price:Number(price),stock:Number(stock)}]);setName('');setCategory('');setPrice('');setStock('');setError('');}
 return <div className={dark?'app dark':'app light'}><aside className="sidebar"><div className="logo"><span className="logoicon"><Package size={19}/></span> NexaShop</div><div className="navitem active"><LayoutDashboard size={17}/> Panel general</div><div className="sidehint">GESTIÓN</div><div className="navitem"><Package size={17}/> Inventario</div><div className="sidebottom">Proyecto académico<br/><small>Panel administrativo</small></div></aside>
 <main className="main"><header className="top"><div><span className="crumb">NexaShop / </span>Panel general</div><button className="iconbtn" onClick={()=>setDark(!dark)} aria-label="Cambiar tema">{dark?<Sun size={17}/>:<Moon size={17}/>}</button></header>
 <section className="content"><div className="heading"><div><p className="eyebrow">RESUMEN DE TIENDA</p><h1>Inventario</h1><p className="muted">Administra los productos de tu catálogo.</p></div>
 <Dialog.Root><Dialog.Trigger asChild><button className="primary"><Plus size={17}/> Nuevo producto</button></Dialog.Trigger><Dialog.Portal><Dialog.Overlay className="overlay"/><Dialog.Content className={dark?'dialog dark':'dialog light'}><div className="dialoghead"><div><Dialog.Title>Agregar producto</Dialog.Title><Dialog.Description>Completa la información para registrar un artículo.</Dialog.Description></div><Dialog.Close asChild><button className="iconbtn"><X size={17}/></button></Dialog.Close></div><form onSubmit={add} className="form"><label>Nombre<input value={name} onChange={e=>setName(e.target.value)} placeholder="Ej. Teclado mecánico"/></label><label>Categoría<input value={category} onChange={e=>setCategory(e.target.value)} placeholder="Ej. Accesorios"/></label><div className="formrow"><label>Precio (COP)<input type="number" min="1" value={price} onChange={e=>setPrice(e.target.value)} placeholder="150000"/></label><label>Unidades<input type="number" min="0" step="1" value={stock} onChange={e=>setStock(e.target.value)} placeholder="10"/></label></div>{error&&<p className="error">{error}</p>}<button className="primary submit" type="submit"><Plus size={16}/> Guardar producto</button></form></Dialog.Content></Dialog.Portal></Dialog.Root></div>
 <div className="metrics"><div className="metric"><span>Productos registrados</span><strong>{products.length}</strong><small>Artículos en catálogo</small></div><div className="metric"><span>Unidades disponibles</span><strong>{products.reduce((s,p)=>s+p.stock,0)}</strong><small>Stock total</small></div><div className="metric"><span>Valor del inventario</span><strong>{money(products.reduce((s,p)=>s+p.price*p.stock,0))}</strong><small>Precio × unidades</small></div></div>
 <section className="tablecard"><div className="tablehead"><div><h2>Productos</h2><p className="muted">Listado actualizado en esta sesión.</p></div><div className="search"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar producto..."/></div></div><div className="tablewrap"><table><thead><tr><th>PRODUCTO</th><th>CATEGORÍA</th><th>PRECIO</th><th>STOCK</th><th>ESTADO</th></tr></thead><tbody>{visible.map(p=><tr key={p.id}><td><div className="prodname"><span className="prodicon"><Package size={16}/></span><b>{p.name}</b></div></td><td>{p.category}</td><td>{money(p.price)}</td><td>{p.stock}</td><td><span className={p.stock<10?'pill low':'pill'}>{p.stock<10?'Stock bajo':'Disponible'}</span></td></tr>)}{visible.length===0&&<tr><td colSpan={5} className="empty">No se encontraron productos.</td></tr>}</tbody></table></div></section><p className="footnote">Los datos se mantienen en memoria mientras la página está abierta; no hay conexión a base de datos.</p></section></main></div>
}